# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f4a30a5520608dfba74d5d909bc3e09fc1c0738946ad651e3244087a7060b3877ec5ce79925283a1544cffc3f5406d1f9c0f6a6d5799f657f3f8f0cbd6c0e015

test:
  secret_key_base: 0efff31345ac0ab05426da9bcb5085f659f418aa9217e64f675e1540e229758d90ef34eef573df36ebbd48ce3dd0d39aa36d805827362dfee71ea07c5e88572e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
